add_newline = true
# format = """$shell$status$directory$git_branch$git_status$git_metrics$lua$docker_context$conda$hostname$localip$cmd_duration$sudo
# $character"""
format = """$all$shell$directory$status$git_branch$git_status$git_metrics$lua$docker_context$conda$hostname$localip$cmd_duration$sudo
$character"""

right_format = "$time"

[line_break]
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = true
read_only = 'ğŸ”’'
fish_style_pwd_dir_length = 0
format = '[\[ğŸ“$path\]]($style) '

[git_branch]
symbol = 'ğŸŒ¿ '
format = '[$symbol$branch]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = 'ğŸš©'
ahead = 'â¬†ï¸ ${count}'
behind = 'â¬‡ï¸ ${count}'
diverged = 'â†•ï¸ â¬†ï¸ ${ahead_count}â¬‡ï¸ ${behind_count}'
up_to_date = 'âœ…'
untracked = 'â“${count}'
stashed = 'ğŸ“¦'
modified = 'ğŸ“${count}'
staged = 'ğŸŸ¢${count}'
renamed = 'ğŸ”„${count}'
deleted = 'ğŸ—‘ï¸${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
added_style = 'bold green'
deleted_style = 'bold red'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[python]
symbol = 'ğŸ‘¾ '
pyenv_version_name = true

[conda]
format = '[$symbol$environment](dimmed green) '

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) [\(ğŸ’»$hostname âœ](bold cyan) '
ssh_symbol = 'ğŸŒ '
disabled = false

# [character]
# success_symbol = '[âœ](bold green)'
# error_symbol = '[âœ—](bold red)'
# disabled = false
[character]
success_symbol = ""
error_symbol = ""

[lua]

[golang]

[nodejs]

[status]
disabled = false

[shell]
disabled = false
powershell_indicator = '_ PS'
format = '[$indicator]($style) '
bash_indicator = " BASH"
zsh_indicator = "âš¡ZSH"
cmd_indicator = "î¯„  cmd"
nu_indicator = "ğŸ”¥ NU"
unknown_indicator = "â“ SHELL"
style = "white bold"

[rust]

[cmd_duration]
disabled = false
min_time = 2000
format = "[ğŸƒ$duration]($style) "

[localip]
ssh_only = false
format = '[ğŸŒ$localipv4\)](bold cyan) '
disabled = false

[time]
disabled = false
style = 'bold yellow'
format = '[ğŸ•™ $time]($style)'
time_format = '%T'

# [sudo]
# style = 'bold red'
# symbol = 'ğŸ’€ADMIN'
# disabled = false
